name: bible_search
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+3

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  # Flutter default dependencies
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

  # External dependencies
  auto_size_text: '>=2.0.1'
  diacritic: ^0.1.1
  draggable_scrollbar: ^0.0.4
  dynamic_theme: ^1.0.1
  flutter_redux: ^0.5.3
  in_app_purchase: ^0.2.1+3
  redux: ^3.0.0
  share: ^0.6.0+1
  transparent_image: ^0.1.0
  url_launcher: ^5.0.1
  
  # Internal dependencies
  tec_ads:
    path: ../shared/tec_ads
  tec_cache:
    path: ../shared/tec_cache
  tec_util:
    path: ../shared/tec_util

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/appimage.jpg
   - assets/Translation.json
   - assets/logo.png
   - assets/1.jpg
   - assets/2.jpg
   - assets/3.jpg
   - assets/4.jpg
   - assets/5.jpg
   - assets/6.jpg
   - assets/7.jpg
   - assets/8.jpg
   - assets/9.jpg
   - assets/10.jpg
   - assets/11.jpg
   - assets/12.jpg
   - assets/13.jpg
   - assets/14.jpg
   - assets/15.jpg
   - assets/16.jpg
   - assets/17.jpg
   - assets/18.jpg
   - assets/19.jpg
   - assets/20.jpg
   - assets/21.jpg
   - assets/22.jpg
   - assets/23.jpg
   - assets/24.jpg
   - assets/25.jpg
   - assets/26.jpg
   - assets/27.jpg
   - assets/28.jpg
   - assets/29.jpg
   - assets/30.jpg
   - assets/31.jpg
   - assets/32.jpg
   - assets/33.jpg
   - assets/34.jpg
   - assets/35.jpg
   - assets/36.jpg
   - assets/37.jpg
   - assets/38.jpg
   - assets/39.jpg
   - assets/40.jpg
   - assets/41.jpg
   - assets/42.jpg
   - assets/43.jpg
   - assets/44.jpg
   - assets/45.jpg
   - assets/46.jpg
   - assets/47.jpg
   - assets/48.jpg
   - assets/49.jpg
   - assets/50.jpg
   - assets/51.jpg
   - assets/52.jpg
   - assets/53.jpg
   - assets/54.jpg
   - assets/55.jpg
   - assets/56.jpg
   - assets/57.jpg
   - assets/58.jpg
   - assets/59.jpg
   - assets/60.jpg
   - assets/61.jpg
   - assets/62.jpg
   - assets/63.jpg
   - assets/64.jpg
   - assets/65.jpg
   - assets/66.jpg
   - assets/67.jpg
   - assets/68.jpg
   - assets/69.jpg
   - assets/70.jpg
   - assets/71.jpg
   - assets/72.jpg
   - assets/73.jpg
   - assets/74.jpg
   - assets/75.jpg
   - assets/76.jpg
   - assets/77.jpg
   - assets/78.jpg
   - assets/79.jpg
   - assets/80.jpg
   - assets/81.jpg
   - assets/82.jpg
   - assets/83.jpg
   - assets/84.jpg
   - assets/85.jpg
   - assets/86.jpg
   - assets/87.jpg
   - assets/88.jpg
   - assets/89.jpg
   - assets/90.jpg
   - assets/91.jpg
   - assets/92.jpg
   - assets/93.jpg
   - assets/94.jpg
   - assets/95.jpg
   - assets/96.jpg
   - assets/97.jpg
   - assets/98.jpg
   - assets/99.jpg
   - assets/100.jpg
   - assets/101.jpg
   - assets/102.jpg
   - assets/103.jpg
   - assets/104.jpg
   - assets/105.jpg
   - assets/106.jpg
   - assets/107.jpg
   - assets/108.jpg
   - assets/109.jpg
   - assets/110.jpg
   - assets/111.jpg
   - assets/112.jpg
   - assets/113.jpg
   - assets/114.jpg
   - assets/115.jpg
   - assets/116.jpg
   - assets/117.jpg
   - assets/118.jpg
   - assets/119.jpg
   - assets/120.jpg
   - assets/121.jpg
   - assets/122.jpg
   - assets/123.jpg
   - assets/124.jpg
   - assets/125.jpg
   - assets/126.jpg
   - assets/127.jpg
   - assets/128.jpg
   - assets/129.jpg
   - assets/130.jpg
   - assets/131.jpg
   - assets/132.jpg
   - assets/133.jpg
   - assets/134.jpg
   - assets/135.jpg
   - assets/136.jpg
   - assets/137.jpg
   - assets/138.jpg
   - assets/139.jpg
   - assets/140.jpg
   - assets/141.jpg
   - assets/142.jpg
   - assets/143.jpg
   - assets/144.jpg
   - assets/145.jpg
   - assets/146.jpg
   - assets/147.jpg
   - assets/148.jpg
   - assets/149.jpg
   - assets/150.jpg
   - assets/151.jpg
   - assets/152.jpg
   - assets/153.jpg
   - assets/154.jpg
   - assets/155.jpg
   - assets/156.jpg
   - assets/157.jpg
   - assets/158.jpg
   - assets/159.jpg
   - assets/160.jpg
   - assets/161.jpg
   - assets/162.jpg
   - assets/163.jpg
   - assets/164.jpg
   - assets/165.jpg
   - assets/166.jpg
   - assets/167.jpg
   - assets/168.jpg
   - assets/169.jpg
   - assets/170.jpg
   - assets/171.jpg
   - assets/172.jpg
   - assets/173.jpg
   - assets/174.jpg
   - assets/175.jpg
   - assets/176.jpg
   - assets/177.jpg
   - assets/178.jpg
   - assets/179.jpg
   - assets/180.jpg
   - assets/181.jpg
   - assets/182.jpg
   - assets/183.jpg
   - assets/184.jpg
   - assets/185.jpg
   - assets/186.jpg
   - assets/187.jpg
   - assets/188.jpg
   - assets/189.jpg
   - assets/190.jpg
   - assets/191.jpg
   - assets/192.jpg
   - assets/193.jpg
   - assets/194.jpg
   - assets/195.jpg
   - assets/196.jpg
   - assets/197.jpg
   - assets/198.jpg
   - assets/199.jpg
   - assets/200.jpg
   - assets/201.jpg
   - assets/202.jpg
   - assets/203.jpg
   - assets/204.jpg
   - assets/205.jpg
   - assets/206.jpg
   - assets/207.jpg
   - assets/208.jpg
   - assets/209.jpg
   - assets/210.jpg
   - assets/211.jpg
   - assets/212.jpg
   - assets/213.jpg
   - assets/214.jpg
   - assets/215.jpg
   - assets/216.jpg
   - assets/217.jpg
   - assets/218.jpg
   - assets/219.jpg
   - assets/220.jpg
   - assets/221.jpg
   - assets/222.jpg
   - assets/223.jpg
   - assets/224.jpg
   - assets/225.jpg
   - assets/226.jpg
   - assets/227.jpg
   - assets/228.jpg
   - assets/229.jpg
   - assets/230.jpg
   - assets/231.jpg
   - assets/232.jpg
   - assets/233.jpg
   - assets/234.jpg
   - assets/235.jpg
   - assets/236.jpg
   - assets/237.jpg
   - assets/238.jpg
   - assets/239.jpg
   - assets/240.jpg
   - assets/241.jpg
   - assets/242.jpg
   - assets/243.jpg
   - assets/244.jpg
   - assets/245.jpg
   - assets/246.jpg
   - assets/247.jpg
   - assets/248.jpg
   - assets/249.jpg
   - assets/250.jpg
   - assets/251.jpg
   - assets/252.jpg
   - assets/253.jpg
   - assets/254.jpg
   - assets/255.jpg
   - assets/256.jpg
   - assets/257.jpg
   - assets/258.jpg
   - assets/259.jpg
   - assets/260.jpg
   - assets/261.jpg
   - assets/262.jpg
   - assets/263.jpg
   - assets/264.jpg
   - assets/265.jpg
   - assets/266.jpg
   - assets/267.jpg
   - assets/268.jpg
   - assets/269.jpg
   - assets/270.jpg
   - assets/271.jpg
   - assets/272.jpg
   - assets/273.jpg
   - assets/274.jpg
   - assets/275.jpg
   - assets/276.jpg
   - assets/277.jpg
   - assets/278.jpg
   - assets/279.jpg
   - assets/280.jpg
   - assets/281.jpg
   - assets/282.jpg
   - assets/283.jpg
   - assets/284.jpg
   - assets/285.jpg
   - assets/286.jpg
   - assets/287.jpg
   - assets/288.jpg
   - assets/289.jpg
   - assets/290.jpg
   - assets/291.jpg
   - assets/292.jpg
   - assets/293.jpg
   - assets/294.jpg
   - assets/295.jpg
   - assets/296.jpg
   - assets/297.jpg
   - assets/298.jpg
   - assets/299.jpg
   - assets/300.jpg
   - assets/301.jpg
   - assets/302.jpg
   - assets/303.jpg
   - assets/304.jpg
   - assets/305.jpg
   - assets/306.jpg
   - assets/307.jpg
   - assets/308.jpg
   - assets/309.jpg
   - assets/310.jpg
   - assets/311.jpg
   - assets/312.jpg
   - assets/313.jpg
   - assets/314.jpg
   - assets/315.jpg
   - assets/316.jpg
   - assets/317.jpg
   - assets/318.jpg
   - assets/319.jpg
   - assets/320.jpg
   - assets/321.jpg
   - assets/322.jpg
   - assets/323.jpg
   - assets/324.jpg
   - assets/325.jpg
   - assets/326.jpg
   - assets/327.jpg
   - assets/328.jpg
   - assets/329.jpg
   - assets/330.jpg
   - assets/331.jpg
   - assets/332.jpg
   - assets/333.jpg
   - assets/334.jpg
   - assets/335.jpg
   - assets/336.jpg
   - assets/337.jpg
   - assets/338.jpg
   - assets/339.jpg
   - assets/340.jpg
   - assets/341.jpg
   - assets/342.jpg
   - assets/343.jpg
   - assets/344.jpg
   - assets/345.jpg
   - assets/346.jpg
   - assets/347.jpg
   - assets/348.jpg
   - assets/349.jpg
   - assets/350.jpg
   - assets/351.jpg
   - assets/352.jpg
   - assets/353.jpg
   - assets/354.jpg
   - assets/355.jpg
   - assets/356.jpg
   - assets/357.jpg
   - assets/358.jpg
   - assets/359.jpg
   - assets/360.jpg
   - assets/361.jpg
   - assets/362.jpg
   - assets/363.jpg
   - assets/364.jpg
   - assets/365.jpg
   - assets/366.jpg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Italic.ttf
          style: italic
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto-MediumItalic.ttf
          style: italic
          weight: 500
        
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
